
# Velocity PID (related to keeping the distance to wall)
PID_vel_P: 1.5 #1.5
PID_vel_I: 0.0 #0.5
PID_vel_D: 0.0 #0.4

# Rotation PID (related to keeping the specified angle to wall)
PID_ang_P: 0.020 #0.020
PID_ang_I: 0.000 #0.000
PID_ang_D: 0.000 #0.000

# Height of hovering
base_height: 1.0

# The default movement speed, distance to reference wall and angle to this wall
movement_speed: -1.0
distance_to_wall: 1.0
angle_to_wall: 45.0


# RANSAC SLAM configuration:
ransac_slam/min_points_in_line: 50
ransac_slam/min_points_in_cloud: 10
ransac_slam/shrink_order: 50
ransac_slam/apf_min_width: 1.4
ransac_slam/apf_min_dist:  0.6
ransac_slam/apf_max_dist:  2.8
ransac_slam/apf_min_angl: -25
ransac_slam/apf_max_angl:  25
ransac_slam/apf_better_q:  true


# VELOCITY SERVER configuration:
velocity_server/roll_min: 1000.0
velocity_server/roll_max: 2000.0
velocity_server/pitch_min: 1000.0
velocity_server/pitch_max: 2000.0
velocity_server/yaw_min: 1000.0
velocity_server/yaw_max: 2000.0
velocity_server/throttle_min: 1000.0
velocity_server/throttle_max: 2000.0
velocity_server/vel_to_pwr: 10.0


# Move function euristic constants
move_epsilon:  0.1


# Move function euristic constants
rot_epsilon: 5
wall_ang_eps: 5
angle_to_pass: 30

