
PID_vel_P: 1.0 #1.5
PID_vel_I: 0.3 #0.5
PID_vel_D: 0.3 #0.4

# Tu = 2.97, Ku = 0.075
PID_ang_P: 0.020 #0.020
PID_ang_I: 0.000 #0.000
PID_ang_D: 0.000 #0.000

base_height: 0.6
vel_to_pwr: 10.0
angle_of_kinect: -45.0

movement_speed: 0.5
distance_to_wall: 1.5
angle_to_wall: -45.0

