
# Velocity PID (related to keeping the distance to wall)
PID_vel_P: 1.0 #1.5
PID_vel_I: 0.3 #0.5
PID_vel_D: 0.3 #0.4

# Rotation PID (related to keeping the specified angle to wall)
PID_ang_P: 0.020 #0.020
PID_ang_I: 0.000 #0.000
PID_ang_D: 0.000 #0.000

# Height of hovering
base_height: 1.0

# How to convert velocity to engine power
vel_to_pwr: 10.0

# The angle of kinect rotation relative to the red arm (negative means clockwise)
angle_of_kinect: -45.0

# The default movement speed, distance to reference wall and angle to this wall
movement_speed: -0.5
distance_to_wall: 1.0
angle_to_wall: 45.0


# Advanced passage finder related constants:
apf_min_width: 1.4
apf_min_dist:  0.6
apf_max_dist:  2.8
apf_min_angl: -25
apf_max_angl:  25
apf_better_q:  1   # 1 is more computationally demanding but gives less false alarms in door detection    


# RANSAC SLAM configuration:
ransac_slam/min_points_in_line: 50
ransac_slam/min_points_in_cloud: 10
ransac_slam/input_cloud_topic: '/sensors/kinect/depth/points'
ransac_slam/output_cloud_topic: '/ransac_slam/flat_cloud'
ransac_slam/shrink_order: 50
ransac_slam/output_cloud_shrinked_topic: '/ransac_slam/shrinked_flat_cloud'
ransac_slam/visualization_topic: '/ransac_slam/markers'
ransac_slam/publish_clouds: true
ransac_slam/fixed_frame: '/odom'
ransac_slam/base_frame: '/base_stabilized'
ransac_slam/output_frame: '/ransac_slam/tf_output'
ransac_slam/publish_tf: true
ransac_slam/use_sonar_data: true
ransac_slam/input_sonar_topic: '/sonar_height'
ransac_slam/output_odom_topic: '/ransac_slam/odom_out'



# Move function euristic constants
move_epsilon:  0.1


# Move function euristic constants
rot_epsilon: 5
wall_ang_eps: 5
angle_to_pass: 30

# Manual control (on/off)
keyboard_control: false


